version: '3.4'

services:
  postgres:
    container_name: postgres
    build: database/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trafmon_database
    volumes:
      # - ./postgres-data:/var/lib/postgresql/data
      - ./database/backups:/home/backups
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5432:5432"

  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb
    ports:
      - "8001:8081"
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/trafmon_database?sslmode=disable
    depends_on:
      - postgres
